Settings.cs

Hey, I noticed that some text was mistyped and corrected it for you. Feel free to check it over one more time to make sure I'm not making a mistake too.
Also, kudos for figuring all this out!

Fix minor misspelled text in UI

---

Gpu/NvidiaGpuTemperatureProvider.cs
HardwareMonitor.cs
Program.cs
Settings.cs

fix: improved GPU temperature reliability

---

app/Properties/Strings.tr.resx

I left some words like "overdrive, ultimate, boost" as is because they're also used in turkish and unable to find meaningful translation

Turkish language support

---

app/Properties/Strings.zh-CN.resx
docs/README.zh-CN.md

1.Added zh-CN translation for README
2.minor adjustment to existing zh-CN translation for ui

Added zh-CN translation for README and minor edit

---

app/Properties/Strings.es.resx

Added Spanish translation for the new options:
- dGPU off in Optimized mode when on USB-charger.
- Minilled related options.

Added Spanish translation for new options

---

app/Properties/Strings.es.resx

Update the Spanish translation file so it has the same fields as the original "Strings.resx", and translated the new items. :)

Update Spanish translation

---

app/Extra.cs
app/Fans.cs
app/HardwareControl.cs
app/Properties/Strings.Designer.cs
app/Properties/Strings.de.resx
app/Properties/Strings.resx

Translated the app to German (German properties were already there, just not translated). I moved a few hardcoded strings to properties in order to localize them. A few words are left English because there are no good German words to put there and we would use the English words anyways.

German translation

---

app/Properties/Strings.pl.resx

Tweaks in declination and words shortening.

Update to Polish translation

---

app/Properties/Strings.es.resx

Added translations for keyboard backlight timeout but they were too large... This is a shorter translation.

Spanish translation small fix

---

app/Properties/Strings.vi.resx

- Add translation for 'Ultimate'
- Words shortening
- Change some words so they have a closer meaning
- Fix a small double space (lol)

Improve Vietnamese Translation.

---

app/Properties/Strings.es.resx

Now the translation will fit the "Updates" button.

Spanish translation fix for "Updates" + more

---

app/Properties/Strings.ko.resx

- Fix: translation was not applied (renamed file name)
- New syntax translation (v0.81)

Update and fix Korean translation

---

app/Properties/Strings.pt-br.resx

Added/updated strings:
```
<data name="VolumeDown" xml:space="preserve">
<value>Abaixar o volume</value>
</data>
<data name="VolumeUp" xml:space="preserve">
<value>Aumentar o volume</value>
</data>
<data name="VolumeMute" xml:space="preserve">
<value>Silenciar microfone</value>
</data>
<data name="WindowTop" xml:space="preserve">
<value>Manter a janela do aplicativo sempre no topo</value>
</data>
<data name="Updates" xml:space="preserve">
<value>Atualizações</value>
</data>
<data name="FnLock" xml:space="preserve">
<value>Processar teclas de atalho Fn+F sem pressionar Fn</value>
</data>
<data name="KillGpuApps" xml:space="preserve">
<value>Parar todos os aplicativos que usam a GPU ao alternar para o modo Eco</value>
</data>
<data name="Boot" xml:space="preserve">
<value>Ao ligar</value> …
```

(PT-BR) Translation update (Strings.pt-br.resx)

---

app/Properties/Strings.pt-br.resx

- Resolved previous translation issues
- Updated:
```
<data name="AutoRefreshTooltip" xml:space="preserve">
<value>Menor taxa de atualização quando estiver na bateria</value>
</data>
```
```
<data name="MinRefreshTooltip" xml:space="preserve">
<value>Taxa de atualização à 60Hz para economizar bateria</value> 
</data>
```
```
<data name="MaxRefreshTooltip" xml:space="preserve">
<value>Taxa de atualização máxima e menor latência</value>
</data>
```
Please offer a version so I can test if everything is working as it should.
I want to be part of the PT-BR translation of this project from now on.

(PT-BR) Translation Update 2 (Strings.pt-br.resx)

---

app/Properties/Strings.it.resx
app/Properties/Strings.resx

Some senteces might be too long for the UI. There could be some typos.
I noticed this project only tonight and it delighted my day as I was looking for a replacement for that shitty software that is called Armoury Crate, I'm amazed at how you managed to implement basically everything in a 4MB .exe, while those idiots bloat your system with 20+ processes and 2.5GB of installation. Keep up the awesome work!

Added first Italian translation

---

app/HardwareControl.cs
app/Properties/Strings.Designer.cs
app/Properties/Strings.resx
app/Settings.Designer.cs
app/Settings.cs

I guess this is not that important, but it would be nice to know how much the battery is degraded. As we already read battery information and show charge/discharge, we can also read and compute battery health.
_(Yeah, my battery is already quite screwed after just 4 months of use. No idea why)_

Added battery health reading to below the battery charge limiter bar.

---

app/Peripherals/Mouse/AsusMouse.cs
app/Peripherals/Mouse/Models/StrixImpactIIWireless.cs
app/Peripherals/PeripheralsProvider.cs

Added support for the Strix Impact II Wireless mouse.
Hint: has the same DPI switching problem as the Keris Wireless has.

Added Rog Strix Impact II Wireless mouse support. 

---

app/AsusMouseSettings.Designer.cs
app/AsusMouseSettings.cs
app/Peripherals/Mouse/AsusMouse.cs
app/Peripherals/Mouse/Models/ChakramX.cs
app/Peripherals/Mouse/Models/GladiusIIIAimpoint.cs
app/Peripherals/Mouse/Models/ROGKerisWireless.cs
app/Peripherals/Mouse/Models/StrixImpactIIWireless.cs
app/Peripherals/Mouse/Models/TUFM4Wireless.cs
app/Properties/Strings.Designer.cs
app/Properties/Strings.resx

This adds another option for supported mice: Button debounce, or sometimes also referred to as button response.
Also made some minor UI adjustments to the mouse window.

Adds Button debounce (button response time) setting for supported mice.

---

app/Extra.Designer.cs
app/Extra.cs
app/Input/InputDispatcher.cs

Just a quick patch I made for myself (and a quick fix for custom commands using the M2 button) -- thought I'd send this upstream in case it's helpful. :)

add as much button support as we can to the RC71 (ROG Ally)

---

app/Peripherals/Mouse/Models/ROGKerisWireless.cs
app/Peripherals/PeripheralsProvider.cs

Hi :) added support for my rog keris evangelion edition mouse. As it turned out, it has different id in contrast to the standard keris mouse.

Support for rog keris eva edition mouse

---

app/AsusMouseSettings.Designer.cs
app/AsusMouseSettings.cs
app/Peripherals/Mouse/AsusMouse.cs
app/Properties/Strings.Designer.cs
app/Properties/Strings.resx

This is some internal improvement for further mice and also to make extensibility easier. The current mice make no use of it yet, but the Harpe Ace, which is almost done, will be the first (and maybe only one) that needs all those extra stuff.
It also improves error handling and out-of-band or empty packets that get send by some mice here and there.

Internal improvements for mouse support

---

app/AsusMouseSettings.cs
app/Peripherals/Mouse/AsusMouse.cs
app/Peripherals/Mouse/Models/PugioII.cs
app/Peripherals/PeripheralsProvider.cs
app/Settings.cs

Support for ROG Pugio II Mouse. This mouse shares the limitation with a few other mice that the DPI profile switching from GHelper does not work (yet).
Also fixes a bug in the UI for animation speed of the lighting (no idea how this bug made it that far to begin with).

Pugio II (P705) Support

---

app/Peripherals/Mouse/Models/Chakram.cs
app/Peripherals/Mouse/Models/TUFM5.cs
app/Peripherals/PeripheralsProvider.cs

Adds support for the ROG Chakram mouse (P704)

Support for ROG Chakram P704

---

app/Peripherals/Mouse/Models/TUFM5.cs

TUF M5 Mouse has 3 profiles, apparently.

TUF M5 has 3 profiles, not just 1

---

app/AppConfig.cs
app/USB/Aura.cs

Added G733PV model to IsStrixLimitedRGB

Added map for Strix 4-Zone RGB

---

app/AnimeMatrix/AniMatrixControl.cs

The AniMe Matrix audio visualizer stops when the audio device is changed and does not restart on its own.
This happens, for example, when you plug-in/connect headphones, or disconnect them.
Currently, you have to re-set the Matrix mode in the settings window to get the visualizer running again.
This will react to audio endpoint changes and restart the audio capture on its own.

Automatically restart matrix audio capture when default device changes.

---

app/Peripherals/Mouse/Models/StrixCarry.cs
app/Peripherals/PeripheralsProvider.cs

Adds support for the Strix Carry mouse (P508).

Support for Strix Carry (P508)

---

app/Peripherals/Mouse/Models/Pugio.cs
app/Peripherals/PeripheralsProvider.cs

Support for ROG Pugio (P503)

---

docs/README.ja-JP.md
docs/README.md
docs/README.zh-CN.md

I created Japanese translated README.

docs: add Japanese README

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
app/Input/InputDispatcher.cs

Hey @seerge, as a power user, I need more control over my keyboard key binds. There's option to change function keys but not actual modifiers. In this PR I added it.

Change modifiers via app config

---

app/AppConfig.cs

Fix Slash Aura on 2025 Zephyrus
