seerge/g-helper

GHelper.csproj
Gpu/AmdAdl2.cs
Gpu/AmdGpuTemperatureProvider.cs
Gpu/IGpuTemperatureProvider.cs
Gpu/NvidiaGpuTemperatureProvider.cs
Program.cs
Settings.cs

- Supports both NVIDIA and AMD discrete GPUs.
- AMD implementation is based on https://github.com/GPUOpen-LibrariesAndSDKs/display-library, but heavily changed to support ADL2. It worked for me against the integrated GPU in G14 2021, but some testing on the 2022 model with AMD is required. Specifically, distinguishing between integrated and discrete GPUs:
https://github.com/ZimM-LostPolygon/g-helper/blob/62ac478761ffbe1e6dc200fc622950342dc3fda1/Gpu/AmdGpuTemperatureProvider.cs#L50
- Immediately update sensors when opening GHelper window. Before, I had to wait a few seconds for the first value...

feat: added GPU temperature indication. 

---

app/Properties/Strings.es.resx

A little rearrangement of the words to avoid cuts like:
"Establece 60Hz para ahorrar batería y vuelve cuando está enchufa**do**"
"Bajar retroiluminación con batería y volver cuando está ench**ufado**"

Spanish translation length fix

---

app/Fans.cs

G-Helper has been very useful since I made the switch from Armoury Crate. But tweaking with the fan levels have been annoying because they don't auto adjust. This is my first open source contribution ever so I'm sorry if my implementation is very elementary. Also, if there are any GitHub etiquettes that I'm not aware of please let me know.

Add fan levels auto-adjust

---

app/AnimeMatrix/AnimeMatrixDevice.cs

Update to the AniMeMatrix code to also support the Zephyrus M16 2023 (GU604). 
I tested it on mine with some GIFs and the Clock. Both look correct not and are no longer scrambled.

Supports AniMeMatrix for Zephyrus M16 2023 (GU604)

---

app/AppConfig.cs
app/Extra.Designer.cs
app/Extra.cs
app/Properties/Strings.Designer.cs
app/Properties/Strings.de.resx
app/Properties/Strings.es.resx
app/Properties/Strings.fr.resx
app/Properties/Strings.it.resx
app/Properties/Strings.resx
app/Properties/Strings.tr.resx
app/Properties/Strings.uk.resx
app/Properties/Strings.zh-CN.resx
app/Properties/Strings.zh-TW.resx
app/Settings.cs

Fixed the incomplete PR [https://github.com/seerge/g-helper/pull/385 ](https://github.com/seerge/g-helper/pull/385 )
Right now, GHelper automatically adjusts the Windows Power Scheme Overlay (Best Energy Saving, Balanced, Best Performance) when you switch performance mode.
I added a checkbox to make this change optional as it might not be desired. If you uncheck the box, GHelper does not modify the power scheme overlay anymore.
This only affects the change of power overlay. Other features, like change of boost behavior, are unaffected by this.
This setting is not per performance mode but global.

Windows power plan changes optional

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/release.yml

Adds GitHub workflows for automatic building, security scans, and release uploading.
- Build: runs the `dotnet build` command for merge requests and the `main` branch; useful for ensuring changes to source did not break the project.
- CodeQL: automates https://codeql.github.com/ and uploads any findings to the `Security` tab of the project (by default only accessible to developers)
- Release: automates `dotnet publish` and uploads the created executable to the new release. Just create the release as normal and the workflow will be started automagically. After it has run, the file will appear in the files section of the release.
- I added the uncompressed `.exe` to the release files to provide users with flexibility with how they want to download the software
- An example of a fully …

Add GitHub workflows

---

app/Input/InputDispatcher.cs

Added hotkeys for using ctrl / shift + vol up / down to control screen / keyboard brightness.
IE - CTRL + Vol Up = screen brightness up, CTRL + Vol Down = screen brightness down. SHIFT controls keyboard brightness.
Trying to adjust the keyboard brightness or screen brightness is painful on the laptop, finding the right keys in the dark / without having to look is difficult. Using CTRL  or SHIFT+ vol up / vol down is much easier to do than FN+F? combo.

Added hotkeys for brightness control.

---

app/Extra.Designer.cs
app/Extra.cs
app/Helpers/ClamshellModeControl.cs
app/Mode/PowerNative.cs
app/Program.cs
app/Properties/Strings.Designer.cs
app/Properties/Strings.resx

This is something less specific to the Zepyhrus line but something that I personally want and others might also like without having to resort to other tools (if they even exist).
If you've used a MacBook, you likely know about Clamshell Mode. When charger, external display, mouse and keyboard are connected and you close the lid, nothing happens. Means: The machine will not go to sleep and can be used as a desktop replacement.
Windows does not support it like that. Windows has a setting for what to do when closing the lid. The setting does not care whether you have a display connected or not, though. You would have to change that setting manually every time, as sometimes you want it to go to sleep when you close the lid (with nothing besides the charger connected) and sometimes you want to …

Automatic Clamshell Mode Toggle

---

app/Helpers/ClamshellModeControl.cs

This should prevent the fake display, that Nvidia Advanced Optimus creates, to confuse the clamshell detection.

Prevent the Nvidia Advanced Optimimus "fake" display to be considered an external display.

---

app/Extra.Designer.cs
app/Extra.cs
app/Helpers/ClamshellModeControl.cs

This fixes some things about clamshell mode:
- It does not touch the settings at all if the settings is not checked
- If unchecked it will always revert to the system default (Sleep)
- Some internal code cleanup and exposing some functions

Clamshell mode fixes

---

app/Peripherals/Mouse/AsusMouse.cs
app/Peripherals/PeripheralsProvider.cs

I disabled the USB packet logger by default as it is not necessary for normal operation. 
It is still enabled for Debug builds or if  `usb_packet_logger` is set to 1 in app config.
Also fixed the hardcoded logging name in the peripheral detection that stayed in there for some reason.

USB packet logger only for debug builds or if enabled in config

---

app/AsusMouseSettings.cs
app/Peripherals/Mouse/AsusMouse.cs
app/Settings.cs

Some fixes for the mouse settings.
- Prevents crashes if the mouse disconnects when the window is open.
- DPI profile is now stored properly so it stays when the mouse is restarted.
- Mouse updates are handled in background to not lock up the UI when the mouse is slow to respond.

Asus mouse fixes

---

app/Helpers/ClamshellModeControl.cs
app/Mode/PowerNative.cs

This allows users to set their lid default action when clamshell is not engaged.
Set `clamshell_default_lid_action` in config.json to any of those values.
0 = Do nothing
1 = Sleep (default)
2 = Hibernate
3 = Shutdown

Clamshell power user settings

---

app/AsusMouseSettings.cs
app/Peripherals/PeripheralsProvider.cs
app/Settings.cs

The deadlocks that happen with the mouse provider due to recent refactoring are now resolved.
I also re-enabled device polling during "RefreshSensors". The reason is, that this is also used to determine whether the mouse is ready for setting changes. The mouse sends no event when it gets turned off. The dongle still stays there and no HID device event is raised. You only know by reading the mouse and finding out that the mouse responds with empty packets.
The performance impact should be negligible as it runs on a separate thread and even that only takes a few ms.
I also changed the calls to "RefreshBatteryForAllDevices" to run in async tasks as the constant USB traffic for refreshing should still not run on main thread. It could lock the UI if the device is slow to respond.
Also fixed a …

ASUS Mouse: Resolved deadlocks

---

app/AsusMouseSettings.cs
app/Peripherals/Mouse/AsusMouse.cs
app/Peripherals/Mouse/Models/ChakramX.cs
app/Peripherals/Mouse/Models/GladiusIII.cs
app/Peripherals/Mouse/Models/GladiusIIIAimpoint.cs
app/Peripherals/Mouse/Models/TUFM4Wireless.cs
app/Peripherals/PeripheralsProvider.cs
app/Settings.cs

TUF Gaming M4 Wireless (P306_Wireless) is now supported (thanks to @alexatthehub for testing and providing data) 
This also adds some general fixes for the mouse system. 
Battery is now only polled every 20s to reduce useless USB traffic, except for when the GHelper window opens. Then it is force-refreshed. Battery polling now happens in background thread to not block the UI.
Added better error handling when the mouse sends unexpected packets.
Some internal housekeeping to allow for easier crafting of new mouse classes with less redundant code.
Fixes the DPI colors on the buttons for mice that have no custom DPI colors in hardware.

Added support for ASUS TUF Gaming M4 Wireless (P306_Wireless) Mouse

---

app/AsusMouseSettings.Designer.cs
app/AsusMouseSettings.cs
app/Peripherals/Mouse/AsusMouse.cs
app/Peripherals/Mouse/Models/ChakramX.cs
app/Peripherals/Mouse/Models/GladiusIIIAimpoint.cs
app/Properties/Strings.Designer.cs
app/Properties/Strings.resx

Mice that support multiple lighting zones can now be configured individually.
Every zone can have its own lighting setting. Changing the "All" zone will overwrite all other zones.
Only supported Zones will be listed. If zoning is active, which means that at least one zone has a different lighting than the others, the "All" zone button will be darker. If zoning is not active it is the other way round. Changing one zone will enable zoning, changing the "All" zone will automatically disable zoning and overwrite all zones.
Zones have fewer lighting modes. Battery State, Comet and Rainbow mode is not supported for zones, only for "all". This is a limitation of the mouse firmware (and there is not much rainbow with only one RGB zone).

Added Lighting zones for supported mice.

---

app/Settings.cs

As I made the mouse refresh time longer, mice can stay longer in the "Not connected" state if the mouse was in standby.
To accommodate for this, the mouse is refreshed automatically when the mouse hovers the button for the device and the mouse is marked as "Not ready".
Otherwise the user had to wait 20s or close and re-open the GHelper window.

Auto refresh mice when hovering the button

---

app/Peripherals/Mouse/Models/ROGKerisWireless.cs
app/Peripherals/PeripheralsProvider.cs

This adds the ROG Keris wireless with _almost_ full support.
One issue is here: You cannot switch the DPI profile. You can do it via the mouse buttons but the mouse does not respond on the AC interface for DPI switching via GHelper. We tested a lot and haven't found any clue how AC does it. There is 0 traffic over the USB Bus that indicates a DPI profile change. The default endpoints, that even work on mice without AC support for DPI switching (like the TUF M4) error out on this mouse (mouse responds with FF AA, which seems to be a general "I don't understand that packet" message). Either it is a firmware bug or ASUS did something goofy here.
We might have to document that for the mouse support. Everything else works fine for this mouse as tested by @1m4g1ne.

Added Rog Keris Wireless

---

app/AsusMouseSettings.Designer.cs
app/AsusMouseSettings.cs
app/Peripherals/Mouse/AsusMouse.cs

This fixes two issues.
1) For mice like the keris that do not support DPI switching, it now allows do switch through the profiles in GHelper to edit all the profiles without having to press the button on the mouse
2) Mice with only a single lighting zone only show the "All" zone.
3) Closing the profile drop down only switches the mouse profile if the profile is different. This reduces unnecessary calls to the mouse firmware.

Mouse support fixes

---

app/AsusMouseSettings.cs
app/Peripherals/Mouse/Models/GladiusIII.cs
app/Peripherals/PeripheralsProvider.cs

Adds support for Gladius III Wireless (P706_Wireless).
Renamed the other Gladius III (P711) to Gladius III Wireless Aimpoint to differentiate them (yeah, ASUS product names are not confusing at all)
Fixes a bug that can crash G-Helper when opening the mouse window.

Adds support for Gladius III Wireless (P706_Wireless).

---

app/AsusMouseSettings.cs
app/Peripherals/Mouse/AsusMouse.cs
app/Peripherals/Mouse/Models/TUFM3.cs
app/Peripherals/PeripheralsProvider.cs

Adds support for the TUF Gaming M3 Mouse.
This also removes the hardcoded packet logger (left it in by accident...ooops) and falls back to the configuration option.

TUF Gaming M3 support

---

app/AnimeMatrix/AnimeMatrixDevice.cs

Back when I made the AniMeMatrix Support for the GU604 (Zephyrus M16 2023), I somehow screwed up the first 10 rows that were shifted by 1 LED in x direction.
This is fixed now.
The frameShift that I introduced back then is not needed anymore, I just had to account for every other row having different amounts of LEDs for the full rows.
I have now tested it with some stripe patterns to make sure they're all straight and not jagged or have shifts.

AniMeMatrix fix for GU604

---

app/AsusMouseSettings.cs
app/Peripherals/Mouse/Models/KerisWirelssAimpoint.cs
app/Peripherals/PeripheralsProvider.cs

Adds support for the ROG Keris Wireless Aimpoint mouse. Model: P709_Wireless

Support for ROG Keris Wireless Aimpoint (P709_Wireless)

---

app/UI/CustomControls.cs

With the recent changes, my setting (dark taskbar, light window) results in light GHelper which was dark before.
So, I added an option to override the light/dark mode detection in the config file.
The setting is called `ui_mode` and can be either `dark `or `light` (case-insensitive) to override the default design. Everything else, or omitting the setting, will result in the current behavior, which is auto detection.

Dark/Light Mode override

---

app/UI/CustomControls.cs

A change that @AudreyAP  requested. 
If you now specify `windows` for `ui_mode` it effectively behaves like it did before the dark mode "fix". This means, it follows the system dark mode state, not the one for apps.
Like before, specifying nothing or anything besides `dark`, `light` or `windows` will do nothing and follow the default behavior, which means: App dark mode

Added windows based dark mode detection via config override

---

app/Peripherals/Mouse/AsusMouse.cs
app/Peripherals/Mouse/Models/HarpeAceAimLab.cs
app/Peripherals/PeripheralsProvider.cs

Mouse support for the ROG Harpe Ace Aim Lab Edition (P713). Mouse is supported wired, via wireless dongle and also through an OMNI Receiver.

Support for ROG Harpe Ace Aim Lab Edition (P713).

---

app/Extra.cs

Therea are backlight levels for different power status, so saving it accordingly.

Save backlight level according to power status

---

app/AsusACPI.cs

When getting default fan curve by GetFanCurve(), CallMethod() returns buffer with size 20, and causes IsInvalidCurve() fail.
It seems other functions only use the first byte of returned buffer; we can safely reduce the buffer size to 16 to fix default fan curve.

Fix default fan curve buffer size

---

app/AppConfig.cs
app/Gpu/GPUModeControl.cs

Fix for GPU mode resetting after system restart. 
I'm having issue on my FX517 when i set GPU to Eco mode and after restarting system it's being reset to Standart. I noticed this issue in Armory Crate after one of it's updates around 8 months ago, though there are no apps that use GPU on startup.
So i propose to add parameter that will force set gpu mode, not only for 503 model.

add force set gpu param

---

app/Peripherals/Mouse/Models/StrixImpactII.cs
app/Peripherals/PeripheralsProvider.cs
app/Settings.cs

Adds support for the ROG Strix Impact II Mouse (Model P506). 
This mouse has the following limitation: No dedicated RGB Off mode. Armoury Crate actually sets the mouse to Static, Red, 0% brightness when you toggle lighting off.
To turn off the light in G-Helper, you have to set the brightness slider to 0% in any mode.
Also made a change to the battery percentage in the main window. The battery state is only shown when the mouse actually has a battery.

Support for ROG Strix Impact II (P506)

---

app/Input/InputDispatcher.cs
app/Program.cs
app/Settings.cs

Before: when g helper window is out of focus/behind a window, pressing the ROG key will make it disappear, thus making the user have to press twice. Additionally, when clicking the taskbar icon, it only focuses on the settings window. This causes issues when you click other sub panel icons as it hides a non-visible window, confusing the user.
After: pressing ROG key will bring the window to top if it is not in focus. Clicking taskbar icon or activating ROG key will focus all previously visible subpanels to top.

feat: improve focus behavior

---

app/Peripherals/Mouse/Models/TUFM5.cs
app/Peripherals/PeripheralsProvider.cs

Adds support for the TUF Gaming M5 Mouse (P304).

Support for TUF Gaming M5 Mouse.

---

app/Peripherals/Mouse/Models/KerisWirelssAimpoint.cs

The Keris Wireless Aimpoint does not support all lighting modes. This disables the unsupported ones.

Remove unsupported lighting modes for  Keris Wireless Aimpoint

---

app/Input/KeyboardHook.cs

After v0.131 update i noticed that FN+F10 doesn't toggle touchpad state at all, in the discussion [#1504](https://github.com/seerge/g-helper/discussions/1504) i meant to add delay before firing all key up events, now it works as it should, even with 50ms delay

fix toggle touchpad

---

app/Settings.Designer.cs
app/Settings.cs

Setting the title bar icon and taskbar icon separately using SendMessage.
fixes #1604 
Should smallBmp and bigBmp be disposed after passing the handle to SendMessage (which was done using [GetHicon()](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.gethicon?view=dotnet-plat-ext-7.0))? Or should it instead just be a oneliner like `Properties.Resources.ultimate.ToBitmap().GetHicon()` ?
SO Solution Link: https://stackoverflow.com/questions/4048910/setting-a-different-taskbar-icon-to-the-icon-displayed-in-the-titlebar-c

setting different icon for taskbar and title bar

---

app/USB/Aura.cs

Ulterior fixes related to #1636 brought up for 15 inches models.

fix: ulterior fixes from #1636

---

app/Peripherals/Mouse/Models/ChakramCore.cs
app/Peripherals/PeripheralsProvider.cs

Adds support for the ROG Chakram Core (P511) mouse.

Added support for ROG Chakram Core (P511)

---

app/Peripherals/Mouse/Models/KerisWirelssAimpoint.cs

On newest firmware (April 2024), on packet 13, instead start from 0 for polling rate values, they bump it to 96. I have a check for someone that use the old firmware, tested on the new one but maybe wait for someone with old firmware check it.

Polling rate fix for Keris Wireless Aimpoint

---

app/Peripherals/Mouse/Models/TUFM4Air.cs

Remove unnecessary overrides from M4 Air
This is just a clean-up as it overrides functions with identical implementations which is not necessary and just adds clutter.

Remove unnecessary overrides from M4 Air

---

app/Peripherals/Mouse/Models/TUFM4Wireless.cs
app/Peripherals/PeripheralsProvider.cs

Support for the TX Gaming Mini (P519). This is a Chinese variant of the TuF M4 Wireless

Tx gaming mini

---

app/AppConfig.cs

Added GA502IU model wih NoAura Devices because has an only static single color keyboard, with no animations; you can only dim it's brightness

Added GA502IU model wih NoAura Devices

---

app/AppConfig.cs

Also I have just spotted there are both OLED and non-OLED SKUs under the same model:
https://www.asus.com/laptops/for-home/zenbook/zenbook-14x-ux5401-11th-gen-intel/techspec/
https://www.asus.com/laptops/for-home/zenbook/zenbook-14x-oled-ux5401-11th-gen-intel/techspec/
Maybe we need some new approach to check OLED.

IsOLED: Add Zenbook S 14 (Intel), Zenbook S 16 (AMD)

---

app/AppConfig.cs
app/AsusACPI.cs
app/Input/InputDispatcher.cs

Add support for CameraShutter on UX5401 and UX5406 to resolve the issue of the LED light not responding on the corresponding button.
See also: https://github.com/Kuchteq/asus-shutter-linux

Add support for CameraShutter

---

app/Input/InputDispatcher.cs

I apologize that my initial PR (#3358 ) did not correctly implement this feature. Initially, although I disabled Secure Boot and used tools like IRPMon to monitor ACPI messages sent by MyASUS, I found that the same DSTS message was sent regardless of whether the Camera was turned on or off. I assumed there was an issue with my monitoring setup, so I looked up asus-shutter-linux on GitHub and referenced that project to implement the relevant logic.
In my environment, OSD is disabled, and I did not run Visual Studio with administrator privileges. Under these conditions, the related keys functioned as expected following the logic from asus-shutter-linux. However, after running the 'scan' function, I noticed that on my machine (which differs from the model indicated in asus-shutter-linux), …

Fix the CameraShutter-related logic on UX5406

---

app/Input/InputDispatcher.cs
app/Peripherals/Mouse/AsusMouse.cs

Without this line of code, if the laptop is shut down while in the "Camera Off" state, the indicator light on the CameraShutter key will remain off after reboot, which does not reflect the actual state of the camera.

Synchronize the indicator light status of CameraShutter at startup.

---

app/Properties/Strings.ar.resx

Hi @seerge 
This PR introduces Arabic language support to G-Helper.
I have translated the existing English strings from `Strings.resx` into Arabic and included them in the new `Strings.ar.resx` file. 
However, during the translation process, I noticed several UI text elements that appear to be hardcoded directly in the source files rather than being sourced from the resource files. 
Here are some examples I spotted:
*   **Main UI Elements:**
*   "Slash Lighting" (and its modes "Bounce, Slash, Loading, Bitstream and whatnot", "Interval Off", and interval values like "Interval Xs") appears in `app/Settings.cs`.
*   "FN-Lock" (and its on/off states for button text and toast notifications) seems to be in `app/Settings.cs` and `app/Input/InputDispatcher.cs`.
*   **Extra Settings UI …

Added Arabic localization (Strings.ar.resx)

---

app/Ryzen/RyzenControl.cs

This is a very simple change that allows for CPU Overvolting in the config file by adding a "max_uv" variable.
I have an odd GA401QM that freezes/BSODs on idle when using the "Best Power Efficiency" power mode without a 15mV overvolt.

Add Overvolt setting for Power Users 
